package es.manolo.demo_jug.data;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.validation.constraints.*;

import java.time.LocalDate;

@Entity
public class Contact {
    // add key id Long autogenerated
    @Id
    @GeneratedValue
    private Long id;
    @NotEmpty
    @Size(min = 3, max = 50, message = "Name must be between 3 and 50 characters")
    private String name;
    @Email
    private String email;
    private String phone;
    @NotEmpty
    private String address;
    @NotEmpty
    private String lastName;
    @Past
    private LocalDate birthDay;

    public Contact() {
    }

    public Contact(String name, String email, String phone, String address, String lastName, LocalDate birthDay) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.lastName = lastName;
        this.birthDay = birthDay;
    }



    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDate getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(LocalDate birthDay) {
        this.birthDay = birthDay;
    }


}
